drop DATABASE BMS_DB;

create DATABASE BMS_DB1;

use BMS_DB1;

CREATE TABLE CUSTOMER_PERSONAL_INFO(
    CUSTOMER_NAME VARCHAR(30),
    CUSTOMER_ID VARCHAR(10),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(30),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    CONSTRAINT CUST_PERK_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);


--CUSTOMER_TABLE_INFCITIZENSHIPO



CREATE TABLE CUSTOMER_REFERENCE_INFO
(
    CUSTOMER_ID VARCHAR(10),
    REFERENCE_ACC_NO VARCHAR(30),
    REFERENCE_ACC_NAME BIGINT(16),
    REFERENCE_ACC_ADDRESS VARCHAR(30),
    RELATION VARCHAR(10),
    CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
    CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUST_PERK_INFO_PK
);

SELECT *,COUNT(AC_NO)
FROM CUSTOMER_REFERENCE_INFO
GROUP BY(AC_NO)
HAVING COUNT(ACC_ID)>1

--BANK INFO

CREATE TABLE BANK_INFO
(
    IFSC_CODE VARCHAR(16),
    BANK_NAME VARCHAR(16),
    BRANCH_NAME VARCHAR(16),
    BANK_ADDRESS VARCHAR(30),
    CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE),

);

SELECT *,COUNT(IFSC_CODE)
FROM BANK_INFO
GROUP BY (IFSC_CODE)
HAVING COUNT(IFSC_CODE)> 1


--CUSTOMER ACCOUNT 

CREATE TABLE ACCOUNT_INFO (
    ACCOUNT_NO VARCHAR(11),
    CUSTOMER_ID VARCHAR(10),
    ACCOUNT_TYPE VARCHAR(10),
    REGISTERATION_DATA DATE,
    IFSC_CODE VARCHAR(10),
    INTEREST DECIMAL(7,2),
    INITIAL_DEPOSIT BIGINT(10),
    CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
    CONSTRAINT CUST_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUST_REF_INFO_PK,
    CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO_PK
)


SELECT * ,COUNT(ACC_NO)
FROM ACCOUNT_INFO
GROUP BY ACC_NO
HAVING COUNT(ACC_NO)>1


INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('SBIN000076','STATE_BANK_OF_INDIA','ADB_FTP');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('CBIN000076','CANARA_BANK_OF_INDIA','KV_ALLD');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('ICICI10056','ICICI BANK ','MB_MUMB');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('SBIN00087','STATE_BANK_OF_INDIA','KV_KNP');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES ('SBIN000873','STATE_BANK_OF_INDIA','MB_FTP');


INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_NAME,CONTACT_NO,CITIZENSHIP) VALUES ('UROOZ','9116324043','4036210412');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_NAME,CONTACT_NO,CITIZENSHIP) VALUES ('VED','8116324042','4021530412');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_NAME,CONTACT_NO,CITIZENSHIP) VALUES ('RISHABH','9116324043','2213320412');
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_NAME,CONTACT_NO,CITIZENSHIP) VALUES ('RISHABH','9116324043','4036242198');



---Subsequent  Querties

--Nth Highest Query

SELECT INITIAL_DEPOSIT FROM ACCOUNT_INFO A2
WHERE N-1 = (
    SELECT COUNT(DISTINCT INITIAL_DEPOSIT)
    FROM ACCOUNT_INFO A2 
    WHERE (A2.INITIAL_DEPOSIT  > A1.INITIAL_DEPOSIT)
)


--2ND HIGHEST QUERY


SELECT INITIAL_DEPOSIT FROM ACCOUNT_INFO 
ORDER BY INITIAL_DEPOSIT DESC


--FIND DUPLICATES