drop DATABASE BMS_DB;

create DATABASE BMS_DB1;

use BMS_DB1;

CREATE TABLE CUSTOMER_TABLE_INFO(
    CUSTOMER_NAME VARCHAR(30),
    CUSTOMER_ID VARCHAR(30),
    DATE_OF_BIRTH DATE,
    GUARDIAN_NAME VARCHAR(30),
    ADDRESS VARCHAR(30),
    CONTACT_NO BIGINT(10),
    MAIL_ID VARCHAR(30),
    GENDER CHAR(1),
    MARITAL_STATUS VARCHAR(10),
    ID_DOC_NO VARCHAR(20),
    CITIZENSHIP VARCHAR(10),
    CONSTRAINT CUST_PERK_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);

