CREATE DATABASE UNIVERSITY;

use UNIVERSITY;

CREATE TABLE STUDENT(
    ENROLLMENT_ID VARCHAR(10),
    NAME VARCHAR(10),
    AGE INT,
    GENDER VARCHAR(10)
)

INSERT INTO STUDENT VALUES('IEC2018049','RISHABH','22','M');
INSERT INTO STUDENT VALUES ('IEC2018035','SHIPRA','22','F');
INSERT INTO STUDENT VALUES ('IEC2018032','MANSI','22','F');

SELECT * FROM STUDENT;


CREATE TABLE FACULTY(
    FAC_ID INT PRIMARY KEY,
    NAME VARCHAR(15) NOT NULL DEFAULT '#####',
    AGE INT,
    COURSES VARCHAR,

)


